import pytest


@pytest.fixture
def apple_response():
    return {'data': [{'id': 'pl.acc464c750b94302b8806e5fcbe56e17',
                      'type': 'playlists',
                      'href': '/v1/catalog/us/playlists/pl.acc464c750b94302b8806e5fcbe56e17',
                      'attributes': {'artwork': {'width': 4320,
                                                 'height': 1080,
                                                 'url': 'https://is3-ssl.mzstatic.com/image/thumb/Features71/v4/49/f0/f6/49f0f636-cefe-0fba-a6a1-01321374e768/source/{w}x{h}cc.jpeg',
                                                 'bgColor': '161d16',
                                                 'textColor1': 'ffffff',
                                                 'textColor2': 'e3aa71',
                                                 'textColor3': 'd0d1d0',
                                                 'textColor4': 'ba8e5f'},
                                     'isChart': False,
                                     'url': 'https://music.apple.com/us/playlist/janet-jackson-no-1-songs/pl.acc464c750b94302b8806e5fcbe56e17',
                                     'lastModifiedDate': '2015-04-11T16:15:51Z',
                                     'name': 'Janet Jackson: No.1 Songs',
                                     'playlistType': 'editorial',
                                     'curatorName': 'Apple Music R&B',
                                     'playParams': {'id': 'pl.acc464c750b94302b8806e5fcbe56e17',
                                                    'kind': 'playlist'},
                                     'description': {'standard': "Few female artists have reached the top of the charts as frequently as Janet Jackson. We've assembled all of her number one hits for a chart-topping collection which confirms her status as the true Queen of pop-R&B.",
                                                     'short': 'The songs that cemented her iconic status.'}},
                      'relationships': {'tracks': {'href': '/v1/catalog/us/playlists/pl.acc464c750b94302b8806e5fcbe56e17/tracks',
                                                   'data': [{'id': '1440831862',
                                                             'type': 'songs',
                                                             'href': '/v1/catalog/us/songs/1440831862',
                                                             'attributes': {'previews': [{'url': 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview128/v4/e9/36/3c/e9363c4d-41a9-8b74-296e-2ac28b0953af/mzaf_4927342180706162387.plus.aac.p.m4a'}],
                                                                            'artwork': {'width': 1500,
                                                                                        'height': 1500,
                                                                                        'url': 'https://is5-ssl.mzstatic.com/image/thumb/Music128/v4/23/cb/6a/23cb6a95-8849-8e48-465d-43862c12b6d2/00602547592361.rgb.jpg/{w}x{h}bb.jpeg',
                                                                                        'bgColor': 'a10b23',
                                                                                        'textColor1': 'e6ebf4',
                                                                                        'textColor2': 'e9be8f',
                                                                                        'textColor3': 'd9beca',
                                                                                        'textColor4': 'db9a7a'},
                                                                            'artistName': 'Janet Jackson',
                                                                            'url': 'https://music.apple.com/us/album/when-i-think-of-you/1440831636?i=1440831862',
                                                                            'discNumber': 1,
                                                                            'genreNames': ['Pop', 'Music'],
                                                                            'durationInMillis': 237485,
                                                                            'releaseDate': '1986-02-04',
                                                                            'name': 'When I Think of You',
                                                                            'isrc': 'USAM18600848',
                                                                            'hasLyrics': True,
                                                                            'albumName': 'Control',
                                                                            'playParams': {'id': '1440831862', 'kind': 'song'},
                                                                            'trackNumber': 6,
                                                                            'composerName': 'Janet Jackson, James Samuel Harris III & Terry Lewis'}},
                                                            {'id': '1440839158',
                                                             'type': 'songs',
                                                             'href': '/v1/catalog/us/songs/1440839158',
                                                             'attributes': {'previews': [{'url': 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview118/v4/35/7d/c2/357dc292-2bec-6ea5-84f2-9bb3798741fa/mzaf_9079208623202625892.plus.aac.p.m4a'}],
                                                                            'artwork': {'width': 1500,
                                                                                        'height': 1500,
                                                                                        'url': 'https://is1-ssl.mzstatic.com/image/thumb/Music118/v4/93/de/8f/93de8f8b-5a4f-a28a-aa84-6696facfe758/00602547592378.rgb.jpg/{w}x{h}bb.jpeg',
                                                                                        'bgColor': '0b1111',
                                                                                        'textColor1': 'f6f6f6',
                                                                                        'textColor2': 'd8d8d8',
                                                                                        'textColor3': 'c6c8c8',
                                                                                        'textColor4': 'afb0b0'},
                                                                            'artistName': 'Janet Jackson',
                                                                            'url': 'https://music.apple.com/us/album/miss-you-much/1440838561?i=1440839158',
                                                                            'discNumber': 1,
                                                                            'genreNames': ['Pop', 'Music'],
                                                                            'durationInMillis': 252333,
                                                                            'releaseDate': '1989-08-22',
                                                                            'name': 'Miss You Much',
                                                                            'isrc': 'USAM10110363',
                                                                            'hasLyrics': True,
                                                                            'albumName': 'Rhythm Nation 1814',
                                                                            'playParams': {'id': '1440839158', 'kind': 'song'},
                                                                            'trackNumber': 8,
                                                                            'composerName': 'James Samuel Harris III & Terry Lewis'}},
                                                            {'id': '1440839549',
                                                             'type': 'songs',
                                                             'href': '/v1/catalog/us/songs/1440839549',
                                                             'attributes': {'previews': [{'url': 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview118/v4/57/f5/c6/57f5c608-2256-4d88-cb0b-45727efb5dde/mzaf_8703925852585313244.plus.aac.p.m4a'}],
                                                                            'artwork': {'width': 1500,
                                                                                        'height': 1500,
                                                                                        'url': 'https://is1-ssl.mzstatic.com/image/thumb/Music118/v4/93/de/8f/93de8f8b-5a4f-a28a-aa84-6696facfe758/00602547592378.rgb.jpg/{w}x{h}bb.jpeg',
                                                                                        'bgColor': '0b1111',
                                                                                        'textColor1': 'f6f6f6',
                                                                                        'textColor2': 'd8d8d8',
                                                                                        'textColor3': 'c6c8c8',
                                                                                        'textColor4': 'afb0b0'},
                                                                            'artistName': 'Janet Jackson',
                                                                            'url': 'https://music.apple.com/us/album/black-cat/1440838561?i=1440839549',
                                                                            'discNumber': 1,
                                                                            'genreNames': ['Pop', 'Music'],
                                                                            'durationInMillis': 290573,
                                                                            'releaseDate': '1989-09-19',
                                                                            'name': 'Black Cat',
                                                                            'isrc': 'USAM18900851',
                                                                            'hasLyrics': True,
                                                                            'albumName': 'Rhythm Nation 1814',
                                                                            'playParams': {'id': '1440839549', 'kind': 'song'},
                                                                            'trackNumber': 16,
                                                                            'composerName': 'Janet Jackson'}},
                                                            {'id': '1440839205',
                                                             'type': 'songs',
                                                             'href': '/v1/catalog/us/songs/1440839205',
                                                             'attributes': {'previews': [{'url': 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview128/v4/c8/b5/ce/c8b5ce04-1dc0-f95e-02fe-3ed01a704bfe/mzaf_8114788682696404868.plus.aac.p.m4a'}],
                                                                            'artwork': {'width': 1500,
                                                                                        'height': 1500,
                                                                                        'url': 'https://is1-ssl.mzstatic.com/image/thumb/Music118/v4/93/de/8f/93de8f8b-5a4f-a28a-aa84-6696facfe758/00602547592378.rgb.jpg/{w}x{h}bb.jpeg',
                                                                                        'bgColor': '0b1111',
                                                                                        'textColor1': 'f6f6f6',
                                                                                        'textColor2': 'd8d8d8',
                                                                                        'textColor3': 'c6c8c8',
                                                                                        'textColor4': 'afb0b0'},
                                                                            'artistName': 'Janet Jackson',
                                                                            'url': 'https://music.apple.com/us/album/love-will-never-do-without-you/1440838561?i=1440839205',
                                                                            'discNumber': 1,
                                                                            'genreNames': ['Pop', 'Music'],
                                                                            'durationInMillis': 350000,
                                                                            'releaseDate': '1989-09-19',
                                                                            'name': 'Love Will Never Do (Without You)',
                                                                            'isrc': 'USAM19500719',
                                                                            'hasLyrics': True,
                                                                            'albumName': 'Rhythm Nation 1814',
                                                                            'playParams': {'id': '1440839205', 'kind': 'song'},
                                                                            'trackNumber': 10,
                                                                            'composerName': 'James Samuel Harris III & Terry Lewis'}},
                                                            {'id': '1440839534',
                                                             'type': 'songs',
                                                             'href': '/v1/catalog/us/songs/1440839534',
                                                             'attributes': {'previews': [{'url': 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview118/v4/90/b8/a9/90b8a9a3-7077-3753-93cb-8eefe9bde953/mzaf_6583299097359231114.plus.aac.p.m4a'}],
                                                                            'artwork': {'width': 1500,
                                                                                        'height': 1500,
                                                                                        'url': 'https://is1-ssl.mzstatic.com/image/thumb/Music118/v4/93/de/8f/93de8f8b-5a4f-a28a-aa84-6696facfe758/00602547592378.rgb.jpg/{w}x{h}bb.jpeg',
                                                                                        'bgColor': '0b1111',
                                                                                        'textColor1': 'f6f6f6',
                                                                                        'textColor2': 'd8d8d8',
                                                                                        'textColor3': 'c6c8c8',
                                                                                        'textColor4': 'afb0b0'},
                                                                            'artistName': 'Janet Jackson',
                                                                            'url': 'https://music.apple.com/us/album/escapade/1440838561?i=1440839534',
                                                                            'discNumber': 1,
                                                                            'genreNames': ['Pop', 'Music'],
                                                                            'durationInMillis': 283973,
                                                                            'releaseDate': '1989-09-19',
                                                                            'name': 'Escapade',
                                                                            'isrc': 'USAM18900717',
                                                                            'hasLyrics': True,
                                                                            'albumName': 'Rhythm Nation 1814',
                                                                            'playParams': {'id': '1440839534', 'kind': 'song'},
                                                                            'trackNumber': 14,
                                                                            'composerName': 'Janet Jackson, James Samuel Harris III & Terry Lewis'}},
                                                            {'id': '1388413850',
                                                             'type': 'songs',
                                                             'href': '/v1/catalog/us/songs/1388413850',
                                                             'attributes': {'previews': [{'url': 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/28/cc/8b/28cc8bb5-9671-aa89-1277-e94c132cc939/mzaf_8308654458623403737.plus.aac.p.m4a'}],
                                                                            'artwork': {'width': 1401,
                                                                                        'height': 1401,
                                                                                        'url': 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/15/17/cf/1517cf41-6401-f679-cc80-ac8e2079ea54/00602567743217.rgb.jpg/{w}x{h}bb.jpeg',
                                                                                        'bgColor': '65666a',
                                                                                        'textColor1': 'f8f0e5',
                                                                                        'textColor2': 'e8d8cc',
                                                                                        'textColor3': 'dbd4cc',
                                                                                        'textColor4': 'cec1b8'},
                                                                            'artistName': 'Janet Jackson',
                                                                            'url': 'https://music.apple.com/us/album/thats-the-way-love-goes/1388413681?i=1388413850',
                                                                            'discNumber': 1,
                                                                            'genreNames': ['Pop', 'Music'],
                                                                            'durationInMillis': 265107,
                                                                            'releaseDate': '1993-04-20',
                                                                            'name': "That's the Way Love Goes",
                                                                            'isrc': 'GBAAA9300170',
                                                                            'hasLyrics': True,
                                                                            'albumName': 'Janet.',
                                                                            'playParams': {'id': '1388413850', 'kind': 'song'},
                                                                            'trackNumber': 2,
                                                                            'composerName': 'Janet Jackson, Terry Lewis & James Harris'}},
                                                            {'id': '1388414162',
                                                             'type': 'songs',
                                                             'href': '/v1/catalog/us/songs/1388414162',
                                                             'attributes': {'previews': [{'url': 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/52/c6/c0/52c6c0a6-3443-7e27-cff6-aff04a9dfc1e/mzaf_1384547821660762987.plus.aac.p.m4a'}],
                                                                            'artwork': {'width': 1401,
                                                                                        'height': 1401,
                                                                                        'url': 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/15/17/cf/1517cf41-6401-f679-cc80-ac8e2079ea54/00602567743217.rgb.jpg/{w}x{h}bb.jpeg',
                                                                                        'bgColor': '65666a',
                                                                                        'textColor1': 'f8f0e5',
                                                                                        'textColor2': 'e8d8cc',
                                                                                        'textColor3': 'dbd4cc',
                                                                                        'textColor4': 'cec1b8'},
                                                                            'artistName': 'Janet Jackson',
                                                                            'url': 'https://music.apple.com/us/album/again/1388413681?i=1388414162',
                                                                            'discNumber': 1,
                                                                            'genreNames': ['Pop', 'Music'],
                                                                            'durationInMillis': 227133,
                                                                            'releaseDate': '1993-05-18',
                                                                            'name': 'Again',
                                                                            'isrc': 'GBAAA9300179',
                                                                            'hasLyrics': True,
                                                                            'albumName': 'Janet.',
                                                                            'playParams': {'id': '1388414162', 'kind': 'song'},
                                                                            'trackNumber': 19,
                                                                            'composerName': 'Janet Jackson, Terry Lewis & James Harris'}},
                                                            {'id': '723390870',
                                                             'type': 'songs',
                                                             'href': '/v1/catalog/us/songs/723390870',
                                                             'attributes': {'previews': [{'url': 'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview118/v4/25/5c/ca/255cca75-1160-1e94-64d8-1ab1ec163fb3/mzaf_6906238375209570047.plus.aac.p.m4a'}],
                                                                            'artwork': {'width': 1404,
                                                                                        'height': 1404,
                                                                                        'url': 'https://is4-ssl.mzstatic.com/image/thumb/Music118/v4/38/12/ab/3812ab15-dcbb-4641-5bab-e7eb35905828/00724384476250.rgb.jpg/{w}x{h}bb.jpeg',
                                                                                        'bgColor': 'a03524',
                                                                                        'textColor1': 'fffecb',
                                                                                        'textColor2': 'fedaa2',
                                                                                        'textColor3': 'ebd5a9',
                                                                                        'textColor4': 'ebb989'},
                                                                            'artistName': 'Janet Jackson',
                                                                            'url': 'https://music.apple.com/us/album/together-again/723390477?i=723390870',
                                                                            'discNumber': 1,
                                                                            'genreNames': ['Pop',
                                                                                           'Music',
                                                                                           'Electronic',
                                                                                           'R&B/Soul',
                                                                                           'Contemporary R&B',
                                                                                           'Adult Contemporary',
                                                                                           'Dance'],
                                                                            'durationInMillis': 301200,
                                                                            'releaseDate': '1997-10-07',
                                                                            'name': 'Together Again',
                                                                            'isrc': 'USVI29700014',
                                                                            'hasLyrics': True,
                                                                            'albumName': 'The Velvet Rope',
                                                                            'playParams': {'id': '723390870', 'kind': 'song'},
                                                                            'trackNumber': 11}},
                                                            {'id': '724885384',
                                                             'type': 'songs',
                                                             'href': '/v1/catalog/us/songs/724885384',
                                                             'attributes': {'previews': [{'url': 'https://audio-ssl.itunes.apple.com/itunes-assets/Music2/v4/69/03/c1/6903c1d7-32c9-85cd-d301-5d4bb4e07125/mzaf_4441152766436868823.plus.aac.p.m4a'}],
                                                                            'artwork': {'width': 1404,
                                                                                        'height': 1404,
                                                                                        'url': 'https://is3-ssl.mzstatic.com/image/thumb/Music4/v4/e7/da/e7/e7dae769-89e6-6d6d-0585-79687fbd7ab2/00724381168752.jpg/{w}x{h}bb.jpeg',
                                                                                        'bgColor': 'ffffff',
                                                                                        'textColor1': '050404',
                                                                                        'textColor2': '452c22',
                                                                                        'textColor3': '373636',
                                                                                        'textColor4': '6a564e'},
                                                                            'artistName': 'Janet Jackson',
                                                                            'url': 'https://music.apple.com/us/album/all-for-you/724885014?i=724885384',
                                                                            'discNumber': 1,
                                                                            'genreNames': ['Pop',
                                                                                           'Music',
                                                                                           'Rock',
                                                                                           'Electronic',
                                                                                           'Pop/Rock',
                                                                                           'R&B/Soul',
                                                                                           'Contemporary R&B',
                                                                                           'Adult Contemporary',
                                                                                           'Dance'],
                                                                            'durationInMillis': 330027,
                                                                            'releaseDate': '2001-03-13',
                                                                            'name': 'All for You',
                                                                            'isrc': 'USVI20100057',
                                                                            'hasLyrics': True,
                                                                            'albumName': 'All for You',
                                                                            'playParams': {'id': '724885384', 'kind': 'song'},
                                                                            'trackNumber': 3}},
                                                            {'id': '724885790',
                                                             'type': 'songs',
                                                             'href': '/v1/catalog/us/songs/724885790',
                                                             'attributes': {'previews': [{'url': 'https://audio-ssl.itunes.apple.com/itunes-assets/Music1/v4/25/51/98/255198f2-02d9-0d8a-183f-9cacee118b2e/mzaf_1901656142812658216.plus.aac.p.m4a'}],
                                                                            'artwork': {'width': 1404,
                                                                                        'height': 1404,
                                                                                        'url': 'https://is3-ssl.mzstatic.com/image/thumb/Music4/v4/e7/da/e7/e7dae769-89e6-6d6d-0585-79687fbd7ab2/00724381168752.jpg/{w}x{h}bb.jpeg',
                                                                                        'bgColor': 'ffffff',
                                                                                        'textColor1': '050404',
                                                                                        'textColor2': '452c22',
                                                                                        'textColor3': '373636',
                                                                                        'textColor4': '6a564e'},
                                                                            'artistName': 'Janet Jackson',
                                                                            'url': 'https://music.apple.com/us/album/doesnt-really-matter/724885014?i=724885790',
                                                                            'discNumber': 1,
                                                                            'genreNames': ['Pop',
                                                                                           'Music',
                                                                                           'Rock',
                                                                                           'Electronic',
                                                                                           'Pop/Rock',
                                                                                           'R&B/Soul',
                                                                                           'Contemporary R&B',
                                                                                           'Adult Contemporary',
                                                                                           'Dance'],
                                                                            'durationInMillis': 264973,
                                                                            'releaseDate': '2001-04-24',
                                                                            'name': "Doesn't Really Matter",
                                                                            'isrc': 'USVI20100098',
                                                                            'hasLyrics': True,
                                                                            'albumName': 'All for You',
                                                                            'playParams': {'id': '724885790', 'kind': 'song'},
                                                                            'trackNumber': 17}}]},
                                        'curator': {'href': '/v1/catalog/us/playlists/pl.acc464c750b94302b8806e5fcbe56e17/curator',
                                                    'data': [{'id': '976439551',
                                                              'type': 'apple-curators',
                                                              'href': '/v1/catalog/us/apple-curators/976439551'}]}}}]}


@pytest.fixture
def gplay_response():
    return [{'kind': 'sj#playlistEntry',
             'id': 'AMaBXymRY7J_cgMgbU0Sz8vdF-AI4I-6r2a8XkXhacGN6AP2vfDiJglygfA1FMbs2vrwMvFX52bbJS3EMM1h5dlzSp8I36VEmQ==',
             'absolutePosition': '01729382256910270462',
             'trackId': 'Tecwhopx5pheivs66bqszubdyhy',
             'creationTimestamp': '1555170814541380',
             'lastModifiedTimestamp': '1555170814541380',
             'deleted': False,
             'source': '2',
             'track': {'kind': 'sj#track',
                       'title': 'Public Service Announcement (interlude)',
                       'artist': 'JAY-Z',
                       'composer': '',
                       'album': 'The Black Album',
                       'albumArtist': 'JAY-Z',
                       'year': 2003,
                       'trackNumber': 10,
                       'genre': 'Hip-Hop/Rap',
                       'durationMillis': '173000',
                       'albumArtRef': [{'kind': 'sj#imageRef',
                                        'url': 'http://lh3.googleusercontent.com/_3ji08eU7E6f7cGZgzZHTS-D-UPx9Cdx1rC-8lyXULmK95AiIj-bvKOc_cwIPZQTputjO6bGn0A',
                                        'aspectRatio': '1',
                                        'autogen': False}],
                       'artistArtRef': [{'kind': 'sj#imageRef',
                                         'url': 'http://lh3.googleusercontent.com/weLyqAyDxXtO4n0f1TpwmG_TLgpAhVK0x3jFnJzWgi9Fz-qbVEoPSd54Swl8CZRe0zJ4e5uw4Q',
                                         'aspectRatio': '2',
                                         'autogen': False}],
                       'playCount': 9,
                       'discNumber': 1,
                       'estimatedSize': '6922486',
                       'trackType': '7',
                       'storeId': 'Tecwhopx5pheivs66bqszubdyhy',
                       'albumId': 'Beuxsnb2og5vxeypi25l4cz2g34',
                       'artistId': ['Axul4z6ed3pmgb5hm5gqx4fta2e'],
                       'nid': 'ecwhopx5pheivs66bqszubdyhy',
                       'trackAvailableForSubscription': True,
                       'trackAvailableForPurchase': True,
                       'albumAvailableForPurchase': False,
                       'explicitType': '1'}},
            {'kind': 'sj#playlistEntry',
             'id': 'AMaBXymRY7J_cgMgbU0Sz8vdF-AI4I-6r2a8XkXhacGN6AP2vfDiJglygfA1FMbs2vrwMvFX52bbJS3EMM1h5dlzSp8I36VEmQ==',
             'absolutePosition': '01921535841011411624',
             'trackId': 'Ttirbxrtyhopooa2wkuifltzpma',
             'creationTimestamp': '1555170881516102',
             'lastModifiedTimestamp': '1555170881516102',
             'deleted': False,
             'source': '2',
             'track': {'kind': 'sj#track',
                       'title': 'Paranoid Android',
                       'artist': 'Radiohead',
                       'composer': '',
                       'album': 'OK Computer',
                       'albumArtist': 'Radiohead',
                       'year': 1997,
                       'trackNumber': 2,
                       'genre': 'Brit Pop/Brit Rock',
                       'durationMillis': '387000',
                       'albumArtRef': [{'kind': 'sj#imageRef',
                                        'url': 'http://lh3.googleusercontent.com/FOJ-SO0djyr7GEFpkMJbiS-dtOltviBJwKF0lkR2F8cK1BY62jAVPfXnv-E_CrkOsfYxOxgb',
                                        'aspectRatio': '1',
                                        'autogen': False}],
                       'artistArtRef': [{'kind': 'sj#imageRef',
                                         'url': 'http://lh3.googleusercontent.com/53cYhGcuBl6tJh4NAsrkxHW2dYReUv27bwrA1nb_KNCrgIKeGjhfl-NmUzsu6mJGoyg1UBuvpDM',
                                         'aspectRatio': '2',
                                         'autogen': False}],
                       'playCount': 1,
                       'discNumber': 1,
                       'estimatedSize': '15491684',
                       'trackType': '7',
                       'storeId': 'Ttirbxrtyhopooa2wkuifltzpma',
                       'albumId': 'Bc5lmah5b34pzehbpiccirz3hme',
                       'artistId': ['A3qpbllyfot4yhqo7isoomtctli'],
                       'nid': 'tirbxrtyhopooa2wkuifltzpma',
                       'trackAvailableForSubscription': True,
                       'trackAvailableForPurchase': True,
                       'albumAvailableForPurchase': False,
                       'explicitType': '2'}}]
