import pytest


# TODO use better test data factory
@pytest.fixture
def apple_tracks_list():
    tracks = [
        {'id': '1234',
         'type': 'songs',
         'href': '/v1/catalog/us/songs/1234',
         'attributes':
         {'previews': [{'url': 'https://'}],
                 'artwork': {},
                 'artistName': 'The Artist',
                 'url': 'https://...',
                 'discNumber': 1,
                 'genreNames': ['Pop', 'Music'],
                 'durationInMillis': 12345,
                 'releaseDate': '2019-09-19',
                 'name': 'Song Name',
                 'isrc': 'USAM123',
                 'albumName': 'Album Name',
                 'playParams': {'id': '1234', 'kind': 'song'},
                 'trackNumber': 8,
                 'composerName': 'This Guy, That Gal',
          },
         }

    ]
    return tracks


@pytest.fixture
def gplay_response():
    return [{'kind': 'sj#playlistEntry',
             'id': 'AMaBXymRY7J_cgMgbU0Sz8vdF-AI4I-6r2a8XkXhacGN6AP2vfDiJglygfA1FMbs2vrwMvFX52bbJS3EMM1h5dlzSp8I36VEmQ==',
             'absolutePosition': '01729382256910270462',
             'trackId': 'Tecwhopx5pheivs66bqszubdyhy',
             'creationTimestamp': '1555170814541380',
             'lastModifiedTimestamp': '1555170814541380',
             'deleted': False,
             'source': '2',
             'track': {'kind': 'sj#track',
                       'title': 'Public Service Announcement (interlude)',
                       'artist': 'JAY-Z',
                       'composer': '',
                       'album': 'The Black Album',
                       'albumArtist': 'JAY-Z',
                       'year': 2003,
                       'trackNumber': 10,
                       'genre': 'Hip-Hop/Rap',
                       'durationMillis': '173000',
                       'albumArtRef': [{'kind': 'sj#imageRef',
                                        'url': 'http://lh3.googleusercontent.com/_3ji08eU7E6f7cGZgzZHTS-D-UPx9Cdx1rC-8lyXULmK95AiIj-bvKOc_cwIPZQTputjO6bGn0A',
                                        'aspectRatio': '1',
                                        'autogen': False}],
                       'artistArtRef': [{'kind': 'sj#imageRef',
                                         'url': 'http://lh3.googleusercontent.com/weLyqAyDxXtO4n0f1TpwmG_TLgpAhVK0x3jFnJzWgi9Fz-qbVEoPSd54Swl8CZRe0zJ4e5uw4Q',
                                         'aspectRatio': '2',
                                         'autogen': False}],
                       'playCount': 9,
                       'discNumber': 1,
                       'estimatedSize': '6922486',
                       'trackType': '7',
                       'storeId': 'Tecwhopx5pheivs66bqszubdyhy',
                       'albumId': 'Beuxsnb2og5vxeypi25l4cz2g34',
                       'artistId': ['Axul4z6ed3pmgb5hm5gqx4fta2e'],
                       'nid': 'ecwhopx5pheivs66bqszubdyhy',
                       'trackAvailableForSubscription': True,
                       'trackAvailableForPurchase': True,
                       'albumAvailableForPurchase': False,
                       'explicitType': '1'}},
            {'kind': 'sj#playlistEntry',
             'id': 'AMaBXymRY7J_cgMgbU0Sz8vdF-AI4I-6r2a8XkXhacGN6AP2vfDiJglygfA1FMbs2vrwMvFX52bbJS3EMM1h5dlzSp8I36VEmQ==',
             'absolutePosition': '01921535841011411624',
             'trackId': 'Ttirbxrtyhopooa2wkuifltzpma',
             'creationTimestamp': '1555170881516102',
             'lastModifiedTimestamp': '1555170881516102',
             'deleted': False,
             'source': '2',
             'track': {'kind': 'sj#track',
                       'title': 'Paranoid Android',
                       'artist': 'Radiohead',
                       'composer': '',
                       'album': 'OK Computer',
                       'albumArtist': 'Radiohead',
                       'year': 1997,
                       'trackNumber': 2,
                       'genre': 'Brit Pop/Brit Rock',
                       'durationMillis': '387000',
                       'albumArtRef': [{'kind': 'sj#imageRef',
                                        'url': 'http://lh3.googleusercontent.com/FOJ-SO0djyr7GEFpkMJbiS-dtOltviBJwKF0lkR2F8cK1BY62jAVPfXnv-E_CrkOsfYxOxgb',
                                        'aspectRatio': '1',
                                        'autogen': False}],
                       'artistArtRef': [{'kind': 'sj#imageRef',
                                         'url': 'http://lh3.googleusercontent.com/53cYhGcuBl6tJh4NAsrkxHW2dYReUv27bwrA1nb_KNCrgIKeGjhfl-NmUzsu6mJGoyg1UBuvpDM',
                                         'aspectRatio': '2',
                                         'autogen': False}],
                       'playCount': 1,
                       'discNumber': 1,
                       'estimatedSize': '15491684',
                       'trackType': '7',
                       'storeId': 'Ttirbxrtyhopooa2wkuifltzpma',
                       'albumId': 'Bc5lmah5b34pzehbpiccirz3hme',
                       'artistId': ['A3qpbllyfot4yhqo7isoomtctli'],
                       'nid': 'tirbxrtyhopooa2wkuifltzpma',
                       'trackAvailableForSubscription': True,
                       'trackAvailableForPurchase': True,
                       'albumAvailableForPurchase': False,
                       'explicitType': '2'}}]
